trigger:
  - develop
  - master

pool:
  name: Pobuca Connect MPN Agents
  demands:
    - Agent.OS -equals Linux

variables:
  - group: XSC Coverage API Keys

steps:
  - task: NodeTool@0
    displayName: "Use Node 10.x"
    inputs:
      versionSpec: 10.x

  - script: npm i
    displayName: npm i

  - script: npm run setSonarqubeVersion
    displayName: npm run setSonarqubeVersion

  - script: npm run build
    displayName: build

  - script: npm test:log
    displayName: npm test:log

  - script: npm test
    displayName: npm test

  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'Pieflow Sonar'
      scannerMode: 'CLI'
      configMode: 'file'
    
  - task: SonarQubeAnalyze@4
  
  - task: SonarQubePublish@4
    inputs:
      pollingTimeoutSec: '300'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: "test-results.xml"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"

  - task: CopyFiles@2
    inputs:
      contents: |
        dist/**
        bin/**
        package.json
        .npmignore
        README.md
      targetFolder: $(Build.ArtifactStagingDirectory)
      
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: XSCPackage
